
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Equipos</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="">TUDAI</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav d-flex">

                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="equipos.phtml">Equipos</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="jugadores.phtml">Jugadores</a>
                  </li>

                 </ul>
              </div>
            </div>
          </nav>
    </header>


    <main class="container">

       
        <form id="team-form" action="add" method="POST" class="my-4">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                      <label for="equipo">Equipo</label>
                      <input id="equipo" name="equipo" type="text" class="form-control">
                      <label for="liga">Liga</label>
                      <input id="liga" name="liga" type="text" class="form-control">
                      <label for="pais">Pais</label>
                      <input id="pais" name="pais" type="text" class="form-control">
                      <label>Imagen del equipo</label>
                    <input name="imagen" type="file" accept="image/*" class="form-control">
                        
                    </div>
                </div>   
            </div>


            <button type="submit" class="btn btn-primary mt-2">Guardar</button>
        </form>

     
        <ul id="team-list" class="list-group">
                
        </ul>

        


    </main>
    


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="./js/equipos.js"></script>
</body>
</html>